name: todo-brick

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -threaded
  dependencies:
    - brick
    - text
    - microlens
    - microlens-th
    - vty
    - vector
    - safe
    - text-zipper

executables:
  todo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-brick

# tests:
#   todo-brick-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - todo-brick
